services:

 web:
  build:
   context: ./
   dockerfile: Dockerfile.prod
  depends_on:
   - db
  command: gunicorn -w 4 -b 0.0.0.0:5000 'anecdoter.web_app:create_app()' web
  volumes:
   - static_volume:/home/app/web/anecdoter/static
  expose:
   - 5000
  env_file:
   - ./.env

 nginx:
  build: ./nginx
  volumes:
   - static_volume:/home/app/web/anecdoter/static
  ports:
   - 80:80
   - 443:443
  depends_on:
   - web
  restart: "always"

 aiobot:
  build:
   context: ./
   dockerfile: Dockerfile.prod
  depends_on:
   - db
  command: python app.py aiobot
  expose:
   - 8444
  env_file:
   - ./.env

 telebot:
  build:
   context: ./
   dockerfile: Dockerfile.prod
  depends_on:
   - db
  command: python app.py telebot
  env_file:
   - ./.env

 db:
  image: postgres
  volumes:
   - postgres_volume:/var/lib/postgresql/data/
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=anecdoter_db

volumes:
  postgres_volume:
  static_volume: