services:

 web:
  build: .
  depends_on:
   - db
  command: python app.py web
  ports:
   - "5000:5000"
  env_file:
   - ./.env

 bot:
  build: .
  depends_on:
   - db
  command: python app.py bot
  env_file:
   - ./.env

 db:
  image: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=anecdoter_db

volumes:
  postgres_data:
