services:

 web:
  build: .
  depends_on:
   - db
  command: python app.py web
  ports:
  - "5000:5000"
  volumes:
  - .:/app
  - ./anecdoter:/app/anecdoter
  env_file:
   - ./.env

 bot:
  build: .
  depends_on:
   - db
  command: python app.py bot
  volumes:
   - .:/app
   - ./anecdoter:/app/anecdoter
  env_file:
   - ./.env

 db:
  image: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=anecdoter_db

volumes:
  postgres_data:

#  volumes:
#  - postgres:/var/lib/postgres
#  - postgres_config:/etc/postgres
#  cap_add:
#  - SYS_NICE
#
#volumes:
#  postgres:
#  postgres_config:

#  volumes:
#  - mysql:/var/lib/mysql
#  - mysql_config:/etc/mysql
#  cap_add:
#  - SYS_NICE
#
#volumes:
#  mysql:
#  mysql_config:
