"""empty message

Revision ID: 3ec9bf25b55a
Revises: 321cbca654f2
Create Date: 2022-08-24 15:39:25.704344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec9bf25b55a'
down_revision = '321cbca654f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('joke', sa.String(length=1024), nullable=False),
    sa.Column('joke_index', sa.Integer(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('words', sa.Column('site', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'site')
    op.drop_table('joke_rating')
    # ### end Alembic commands ###
