"""empty message

Revision ID: 58c609689548
Revises: 3ec9bf25b55a
Create Date: 2022-08-25 10:20:08.666497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c609689548'
down_revision = '3ec9bf25b55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rated_jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('joke', sa.String(length=1024), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('joke_rating')
    op.drop_column('words', 'site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('site', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_table('joke_rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('joke', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('joke_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='joke_rating_pkey')
    )
    op.drop_table('rated_jokes')
    # ### end Alembic commands ###
