"""empty message

Revision ID: 794337257346
Revises: 81ee76cf3b8b
Create Date: 2022-08-25 11:57:30.402448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794337257346'
down_revision = '81ee76cf3b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rated_jokes', 'joke')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rated_jokes', sa.Column('joke', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
