"""empty message

Revision ID: 81ee76cf3b8b
Revises: 58c609689548
Create Date: 2022-08-25 11:25:50.356905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ee76cf3b8b'
down_revision = '58c609689548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rated_jokes', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rated_jokes', 'position')
    # ### end Alembic commands ###
