"""empty message

Revision ID: 22a4f3b18c2a
Revises: 62082ad24739
Create Date: 2022-12-01 12:50:49.720207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a4f3b18c2a'
down_revision = '62082ad24739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('login', sa.String(length=64), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'login')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
