"""empty message

Revision ID: d29f5934786d
Revises: e49219a67a3d
Create Date: 2022-12-16 15:18:22.120194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29f5934786d'
down_revision = 'e49219a67a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_chat_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'chat_id')
    op.add_column('words', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('words_chat_id_fkey', 'words', type_='foreignkey')
    op.create_foreign_key(None, 'words', 'users', ['user_id'], ['user_id'])
    op.drop_column('words', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.create_foreign_key('words_chat_id_fkey', 'words', 'users', ['chat_id'], ['chat_id'])
    op.drop_column('words', 'user_id')
    op.add_column('users', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_chat_id_key', 'users', ['chat_id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
